replicaCount: 4
image:
  repository: 'hmuendel/xmrig'

  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 400m
    memory: 50Mi
  requests:
    cpu: 400m
    memory: 50Mi    
args:
  - "--url=pool.monero.hashvault.pro:3333"
  - "--user=48PoncCgLShDQCRZEjEzdLff8BUHXWUKVUtSZcx8UNrGNMY9RjpVi5L7MJhfr1C726UciGs1kPWt7JZfR7aZR8phKDtrwxy"
  - "--pass=$(MY_POD_NAME):someone-used-the-default-wallet"
  - "-k"  
  - "--url=pool.supportxmr.com:3333"
  - "--user=48PoncCgLShDQCRZEjEzdLff8BUHXWUKVUtSZcx8UNrGNMY9RjpVi5L7MJhfr1C726UciGs1kPWt7JZfR7aZR8phKDtrwxy"
  - "--pass=$(MY_POD_NAME):someone-used-the-default-wallet"
  - "-k"
  - "--donate-level=1"
  - "--max-cpu-usage=100"
  - "--cpu-priority 4"


